import os
import json
import re
from llama_cpp import Llama
from tools import mcp_tools

class LLMAgent:
    def __init__(self, model_filename="qwen2.5-7b-instruct-q4_k_m.gguf"):
        base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        self.model_path = os.path.join(base_dir, "model", model_filename)
        
        if not os.path.exists(self.model_path):
            print(f"\n[!] WARNING: Model not found at {self.model_path}")
            print("Please download a .gguf file and place it in the model folder.\n")
            self.llm = None
            return

        print("Loading model into memory... (this might take a moment)")
        self.llm = Llama(model_path=self.model_path, n_gpu_layers=15, n_ctx=4096, verbose=False)

        self.system_prompt = (
            "You are an AI operating an ABB GoFa robot. Your goal is to assist the user by executing robot commands and processing drawings.\n"
            "CURRENT PEN DOWN Z HEIGHT: {CURRENT_PEN_Z}\n"
            "CURRENT SAFE CENTER Z HEIGHT: {CURRENT_SAFE_Z}\n\n"
            "CRITICAL WORKFLOW RULES:\n"
            "1. You MUST connect to the robot first. Do not attempt to move, test, process images, or draw until the connect_robot tool has been successfully executed.\n"
            "2. After connecting, ask the user if they want to test the robot's calibration (e.g., test workspace, go home, test safe center Z).\n"
            "3. Only after the robot is connected should you ask which image they want to draw.\n"
            "4. If the user wants to adjust the pen down Z height, use the set_pen_down_z tool.\n"
            "5. If the user wants to adjust the safe center Z height, use the set_safe_center_z tool.\n\n"
            "You have access to the following tools. To call a tool, you MUST output a VALID JSON block wrapped exactly in ```tool_call and ```.\n"
            "DO NOT output function calls. Output ONLY standard JSON formatted EXACTLY like this:\n"
            "```tool_call\n"
            "{\"name\": \"tool_name\", \"arguments\": {\"arg_name\": \"value\"}}\n"
            "```\n\n"
            "AVAILABLE TOOLS:\n"
            "1. connect_robot\n"
            "   Description: Connects to the robot.\n"
            "   Arguments: {\"mode\": \"simulation\" or \"real\"}\n"
            "2. robot_action\n"
            "   Description: Executes a single movement or test.\n"
            "   Arguments: {\"action_type\": \"home\"|\"safe_center\"|\"test_z\"|\"test_workspace\", \"z_val\": float (optional)}\n"
            "3. pack_robot\n"
            "   Description: Folds the robot for shipping. ALWAYS ask for confirmation first.\n"
            "   Arguments: {\"confirm_checklist\": bool}\n"
            "4. process_image\n"
            "   Description: Reads an image path, processes it, and returns threshold options.\n"
            "   Arguments: {\"filepath\": \"path/to/image.png\"}\n"
            "5. start_drawing\n"
            "   Description: Starts drawing an option generated by process_image.\n"
            "   Arguments: {\"option_label\": \"Option 1\", \"pen_down_z\": float (optional)}\n"
            "6. control_drawing\n"
            "   Description: Controls the background drawing process.\n"
            "   Arguments: {\"command\": \"pause\"|\"resume\"|\"cancel\"|\"status\"}\n"
            "7. set_pen_down_z\n"
            "   Description: Sets the global pen down Z height for drawing.\n"
            "   Arguments: {\"z_val\": float}\n"
            "8. set_safe_center_z\n"
            "   Description: Sets the global safe center Z height.\n"
            "   Arguments: {\"z_val\": float}\n\n"
            "Wait for the System tool execution result before continuing. Only output ONE tool call at a time."
        )

        self.history = []

        self.available_tools = {
            "connect_robot": mcp_tools.connect_robot,
            "robot_action": mcp_tools.robot_action,
            "pack_robot": mcp_tools.pack_robot,
            "process_image": mcp_tools.process_image,
            "start_drawing": mcp_tools.start_drawing,
            "control_drawing": mcp_tools.control_drawing,
            "set_pen_down_z": mcp_tools.set_pen_down_z,
            "set_safe_center_z": mcp_tools.set_safe_center_z
        }

    def _format_prompt(self) -> str:
        """Manually constructs the exact ChatML format, injecting dynamic state."""
        dynamic_sys = self.system_prompt.replace("{CURRENT_PEN_Z}", str(mcp_tools.CURRENT_PEN_DOWN_Z))
        dynamic_sys = dynamic_sys.replace("{CURRENT_SAFE_Z}", str(mcp_tools.CURRENT_SAFE_CENTER_Z))
        prompt = f"<|im_start|>system\n{dynamic_sys}<|im_end|>\n"
        
        for turn in self.history:
            role = turn["role"]
            content = turn["content"]
            prompt += f"<|im_start|>{role}\n{content}<|im_end|>\n"
            
        prompt += "<|im_start|>assistant\n"
        return prompt

    def process_user_input(self, text: str):
        if not self.llm: 
            yield "Model not loaded. Please add the .gguf file."
            return

        self.history.append({"role": "user", "content": text})
        yield from self._generate_response()

    def _generate_response(self, depth=0):
        # Anti-Infinite Loop Guardrail
        if depth > 4:
            error_msg = "[System Safety: Max tool loop depth reached. Aborting automation to prevent infinite loop.]"
            yield f"\n\n{error_msg}\n\n"
            self.history.append({"role": "system", "content": error_msg})
            return

        full_prompt = self._format_prompt()

        stream_resp = self.llm.create_completion(
            prompt=full_prompt,
            temperature=0.2, 
            max_tokens=1024,
            stop=["<|im_end|>", "<|im_start|>"],
            stream=True
        )
        
        full_text = ""
        for chunk in stream_resp:
            delta = chunk["choices"][0]["text"]
            full_text += delta
            yield delta
            
        self.history.append({"role": "assistant", "content": full_text.strip()})
        
        # Use a more forgiving regex that catches single-line outputs
        match = re.search(r'```tool_call\s*(.*?)\s*```', full_text, re.DOTALL)
        if match:
            tool_json_str = match.group(1).strip()
            
            # Fallback: Auto-correct if the LLM hallucinates function-call syntax (e.g., connect_robot({"mode": "real"}))
            func_call_match = re.match(r'^([a-zA-Z_][a-zA-Z0-9_]*)\s*\((.*)\)$', tool_json_str, re.DOTALL)
            if func_call_match:
                extracted_name = func_call_match.group(1)
                extracted_args = func_call_match.group(2).strip()
                if not extracted_args:
                    extracted_args = "{}"
                # Normalize it back to a JSON object string
                tool_json_str = f'{{"name": "{extracted_name}", "arguments": {extracted_args}}}'

            try:
                tool_data = json.loads(tool_json_str)
                
                # Extract the tool name
                tool_name = tool_data.get("name") or tool_data.get("tool")
                
                if "arguments" in tool_data:
                    tool_args = tool_data.get("arguments", {})
                else:
                    # Extract any leftover keys as arguments
                    tool_args = {k: v for k, v in tool_data.items() if k not in ["name", "tool"]}
                
                if tool_name in self.available_tools:
                    yield f"\n\n[⚙️ System: Executing '{tool_name}'...]\n"
                    try:
                        result = self.available_tools[tool_name](**tool_args)
                    except Exception as e:
                        result = f"Error executing tool: {str(e)}"
                    yield f"[⚙️ System: Tool returned: {result}]\n\n"
                    
                    self.history.append({
                        "role": "user", 
                        "content": f"System tool execution result:\n{result}\n(If the user request is complete, summarize the outcome. If more steps are needed, call the next tool.)"
                    })
                    yield from self._generate_response(depth + 1)
                else:
                    error_msg = f"System error: Tool '{tool_name}' does not exist."
                    yield f"\n\n[{error_msg}]\n\n"
                    self.history.append({"role": "user", "content": error_msg})
                    yield from self._generate_response(depth + 1)
                    
            except json.JSONDecodeError:
                error_msg = f"System error: Invalid JSON format in tool call -> {tool_json_str}. Please ensure it is strictly valid JSON."
                yield f"\n\n[{error_msg}]\n\n"
                self.history.append({"role": "user", "content": error_msg})
                yield from self._generate_response(depth + 1)