import os
import json
import re
from llama_cpp import Llama
from tools import mcp_tools

class LLMAgent:
    def __init__(self, model_filename="qwen2.5-7b-instruct-q4_k_m.gguf"):
        base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        self.model_path = os.path.join(base_dir, "model", model_filename)
        
        if not os.path.exists(self.model_path):
            print(f"\n[!] WARNING: Model not found at {self.model_path}")
            print("Please download a .gguf file and place it in the model folder.\n")
            self.llm = None
            return

        print("Loading model into memory... (this might take a moment)")
        # Kept layers low for stability, turned verbose off for clean terminal
        self.llm = Llama(model_path=self.model_path, n_gpu_layers=15, n_ctx=4096, verbose=False)

        # Updated system prompt enforcing the connection-first workflow
        self.system_prompt = (
            "You are an AI operating an ABB GoFa robot. Your goal is to assist the user by executing robot commands and processing drawings.\n"
            "CRITICAL WORKFLOW RULES:\n"
            "1. You MUST connect to the robot first. Do not attempt to move, test, process images, or draw until the connect_robot tool has been successfully executed.\n"
            "2. After connecting, ask the user if they want to test the robot's calibration (e.g., test workspace, go home, test safe center Z).\n"
            "3. Only after the robot is connected should you ask which image they want to draw.\n\n"
            "You have access to the following tools. To call a tool, you MUST output a JSON block wrapped exactly in ```tool_call and ```.\n\n"
            "AVAILABLE TOOLS:\n"
            "1. connect_robot\n"
            "   Description: Connects to the robot.\n"
            "   Arguments: {\"mode\": \"simulation\" or \"real\"}\n"
            "2. robot_action\n"
            "   Description: Executes a single movement or test.\n"
            "   Arguments: {\"action_type\": \"home\"|\"safe_center\"|\"test_z\"|\"test_workspace\", \"z_val\": float (default -10.0)}\n"
            "3. pack_robot\n"
            "   Description: Folds the robot for shipping. ALWAYS ask for confirmation first.\n"
            "   Arguments: {\"confirm_checklist\": bool}\n"
            "4. process_image\n"
            "   Description: Reads an image path, processes it, and returns threshold options. Example: 'C:/images/test.png'\n"
            "   Arguments: {\"filepath\": \"path/to/image.png\"}\n"
            "5. start_drawing\n"
            "   Description: Starts drawing an option generated by process_image.\n"
            "   Arguments: {\"option_label\": \"Option 1\", \"pen_down_z\": float}\n"
            "6. control_drawing\n"
            "   Description: Controls the background drawing process.\n"
            "   Arguments: {\"command\": \"pause\"|\"resume\"|\"cancel\"|\"status\"}\n\n"
            "TOOL CALL FORMAT EXAMPLE:\n"
            "```tool_call\n"
            "{\n"
            "  \"name\": \"connect_robot\",\n"
            "  \"arguments\": {\"mode\": \"simulation\"}\n"
            "}\n"
            "```\n"
            "Wait for the System tool execution result before continuing. Only output ONE tool call at a time. If no tool is needed, converse naturally."
        )

        self.history = []

        self.available_tools = {
            "connect_robot": mcp_tools.connect_robot,
            "robot_action": mcp_tools.robot_action,
            "pack_robot": mcp_tools.pack_robot,
            "process_image": mcp_tools.process_image,
            "start_drawing": mcp_tools.start_drawing,
            "control_drawing": mcp_tools.control_drawing
        }

    def _format_prompt(self) -> str:
        """Manually constructs the exact ChatML format."""
        prompt = f"<|im_start|>system\n{self.system_prompt}<|im_end|>\n"
        
        for turn in self.history:
            role = turn["role"]
            content = turn["content"]
            prompt += f"<|im_start|>{role}\n{content}<|im_end|>\n"
            
        prompt += "<|im_start|>assistant\n"
        return prompt

    def process_user_input(self, text: str):
        if not self.llm: 
            yield "Model not loaded. Please add the .gguf file."
            return

        self.history.append({"role": "user", "content": text})
        yield from self._generate_response()

    def _generate_response(self):
        """Generates response, detects tool calls, executes them, and recursively loops if needed."""
        full_prompt = self._format_prompt()

        stream_resp = self.llm.create_completion(
            prompt=full_prompt,
            temperature=0.2, # Lower temperature for stable JSON formatting
            max_tokens=1024,
            stop=["<|im_end|>", "<|im_start|>"],
            stream=True
        )
        
        full_text = ""
        for chunk in stream_resp:
            delta = chunk["choices"][0]["text"]
            full_text += delta
            yield delta
            
        self.history.append({"role": "assistant", "content": full_text.strip()})
        
        # Check if the LLM attempted to execute a tool block
        match = re.search(r'```tool_call\n(.*?)\n```', full_text, re.DOTALL)
        if match:
            tool_json_str = match.group(1)
            try:
                tool_data = json.loads(tool_json_str)
                tool_name = tool_data.get("name")
                tool_args = tool_data.get("arguments", {})
                
                if tool_name in self.available_tools:
                    yield f"\n\n[⚙️ System: Executing '{tool_name}'...]\n"
                    try:
                        result = self.available_tools[tool_name](**tool_args)
                    except Exception as e:
                        result = f"Error executing tool: {str(e)}"
                    yield f"[⚙️ System: Tool returned: {result}]\n\n"
                    
                    # Feed the result back as a system-like user prompt
                    self.history.append({
                        "role": "user", 
                        "content": f"System tool execution result:\n{result}\n(If the user request is complete, summarize the outcome. If more steps are needed, call the next tool.)"
                    })
                    # Recursively yield the follow-up response
                    yield from self._generate_response()
                else:
                    error_msg = f"System error: Tool '{tool_name}' does not exist."
                    yield f"\n\n[{error_msg}]\n\n"
                    self.history.append({"role": "user", "content": error_msg})
                    yield from self._generate_response()
                    
            except json.JSONDecodeError:
                error_msg = "System error: Invalid JSON format in tool call. Please ensure it is valid JSON."
                yield f"\n\n[{error_msg}]\n\n"
                self.history.append({"role": "user", "content": error_msg})
                yield from self._generate_response()